---
version: "3.4"
services:
  web:
    image: "${DOCKER_IMAGE_NAME:-hapi_fhir}:${DOCKER_IMAGE_TAG:-latest}"
    build: .
    ports:
      - target: 8080
        # change as needed (eg reverse proxy)
        published: ${EXTERNAL_PORT:-8080}
